# Generated by Django 4.1.7 on 2023-05-01 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_status_remove_usersettings_user_usersettings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='id',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_settings', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
