version: '3'
services:
  django:
    build:
    context: ./PythonProject
    container_name: Django
    volumes:
      - .:/code/
    ports:
      - '8080:8080'
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - pgdb
    command: python manage.py runserver 0.0.0.0:8080
  
  celery:
    build: .
    command: celery worker --app=pythonProject --loglevel=info



    # celery:
    #   build:
    #   context: .
    #   dockerfile: Dockerfile.redis_celery
    #   networks:
    #   - project_python
    # command: bash -c "redis-server --daemonize yes && celery -A pythonProject worker --loglevel=info"