# Generated by Django 4.1.7 on 2023-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0002_flashcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='correct_at_row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
