# Generated by Django 4.1.7 on 2023-04-07 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0002_alter_flashcard_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='backText',
            new_name='back_text',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='correctAtRow',
            new_name='correct_at_row',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='frontText',
            new_name='front_text',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='nextSession',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='dailyFlashcards',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='maximumBreak',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='percentNew',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_session',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='daily_flashcards',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='maximum_break',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='percent_new',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='status',
            field=models.CharField(choices=[('NEW', 'Card not learned'), ('LEARNED', 'Card learned')], default='NEW', max_length=15),
        ),
    ]
