# Generated by Django 4.1.7 on 2023-04-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0004_rename_user_flashcard_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='user_id',
            new_name='user',
        ),
    ]
