# Generated by Django 4.1.7 on 2023-04-30 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0005_rename_user_id_flashcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='next_session',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
