# Generated by Django 4.1.7 on 2023-04-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCards', '0006_alter_flashcard_next_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='back_text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front_text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
